//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.24 at 07:38:38 PM MESZ 
//


package rest;

import java.util.ArrayList;
import java.util.List;

import model.User;

import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * <p>Java class for basketList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="basketList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="baskets" type="{http://backend.smartshopper.jku.at/}basket" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class UserList {

	@JsonProperty("user")
    protected List<User> theusers;

    /**
     * Gets the value of the baskets property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the baskets property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBaskets().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Basket }
     * 
     * 
     */
    public List<User> getUsers() {
        if (theusers == null) {
        	theusers = new ArrayList<User>();
        }
        return this.theusers;
    }
    
    public int getLength() {
        return theusers.size();
    }

}
